### ISSUE TITLE
Error when downloading Source for DNN 07.04.02

### ISSUE THREAD

**Issue by deskpal** [dnnsoftware/Dnn.Releases.Archive.7x#1]
Trying to download the source of DNN 07.04.02 but when I navigate to its location here on github:
https://github.com/dnnsoftware/Dnn.Releases.Archive.7x/blob/master/07.04.02/DNN_Platform_07.04.02_Source.zip

and click the download button I get this error:

_This media.githubusercontent.com page can’t be found No webpage was found for the web address: https://media.githubusercontent.com/media/dnnsoftware/Dnn.Releases.Archive.7x/master/07.04.02/DNN_Platform_07.04.02_Source.zip
HTTP ERROR 404_

Thank you,
Aderson

**Comment by deskpal** [comment]
seemed to be a temp problem.

**Comment by david-poindexter** [comment]
Glad it started working.  I have seen some clunkiness with GitHub LFS (Large File Storage).
